name: Build and Publish

on:
  push:
    branches: [master]
  pull_request:

jobs:
  build-and-push-docker-image:
    name: Build image and push to Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: 8
          tags: |
            opcycle/openjdk:8 
          push: ${{ github.ref == 'refs/heads/master' }}
      
      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: 11
          tags: |
            opcycle/openjdk:11 
          push: ${{ github.ref == 'refs/heads/master' }}

      - name: Build image and push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          # relative path to the place where source code with Dockerfile is located
          context: latest
          tags: |
            opcycle/openjdk:latest 
          push: ${{ github.ref == 'refs/heads/master' }}
